<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="Css">
	<title>Banderas del mundo</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="fondo" id="Laos">
		<div class="img">
		<img src="img/circulol.png" width="55%" height="55%"></div>
        <div class="Franja1"></div>
		<div class="Franja2"></div>
		<div class="Franja3"></div>
		

    <div class="fondo" id="Madagascar"> 
        <div class="frranja1"></div>
        <div class="frranja2"></div>
        <div class="frranja3"></div></div>

    <div class="fondo" id="Mexico">
        <div class="frrranja1"> </div>
        <div class="imag">
        <img src="img/mexco2.png" width="50%" height="50%" ></div>
        <div class="frrranja2"> </div>
        <div class="frrranja3"> </div>
    </div>
        


</body>
</html>